//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exchange()
        {
            this.Exchange_Quantity = new HashSet<Exchange_Quantity>();
        }
    
        public int Real_ID { get; set; }
        public int I_ID { get; set; }
        public int C_ID { get; set; }
        public int W_ID { get; set; }
        public System.DateTime Exch_Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchange_Quantity> Exchange_Quantity { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
